#!/usr/bin/env python3
"""Generate questions-extra.js to expand main category pools to 60 questions each."""

import json
from pathlib import Path

TARGET = 60

# Each entry: (question, [opts], ans_index, diff, hint)
EXTRA = {
    "premier-league": [
        ("Which club won the first Premier League title in 1992-93?", ["Arsenal", "Manchester United", "Aston Villa", "Norwich City"], 1, "medium", "Managed by Sir Alex Ferguson."),
        ("Who scored the fastest goal in Premier League history?", ["Shane Long", "Ledley King", "Alan Shearer", "Sadio Mane"], 0, "hard", "7.69 seconds for Southampton vs Watford."),
        ("Which player won the Premier League Golden Boot in 2023-24?", ["Mohamed Salah", "Erling Haaland", "Cole Palmer", "Ollie Watkins"], 1, "easy", "Manchester City striker."),
        ("What is Tottenham Hotspur's home stadium called?", ["Emirates Stadium", "London Stadium", "Tottenham Hotspur Stadium", "Selhurst Park"], 2, "easy", "Opened in 2019 in north London."),
        ("Which club did Virgil van Dijk join Liverpool from?", ["Celtic", "Southampton", "Groningen", "Feyenoord"], 1, "easy", "January 2018 transfer."),
        ("Who managed Chelsea to the 2016-17 Premier League title?", ["Jose Mourinho", "Antonio Conte", "Thomas Tuchel", "Maurizio Sarri"], 1, "medium", "Italian coach, 3-4-3 system."),
        ("Which team was relegated with the fewest points in Premier League history?", ["Sunderland", "Derby County", "Sheffield United", "Huddersfield Town"], 1, "medium", "11 points in 2007-08."),
        ("Who is Newcastle United's all-time leading goalscorer?", ["Alan Shearer", "Jackie Milburn", "Peter Beardsley", "Les Ferdinand"], 0, "medium", "Also the Premier League's record scorer."),
        ("Which club plays at the Amex Stadium?", ["Brighton & Hove Albion", "Crystal Palace", "Bournemouth", "Fulham"], 0, "easy", "Based on the south coast."),
        ("Who won the PFA Players' Player of the Year in 2023-24?", ["Phil Foden", "Cole Palmer", "Ollie Watkins", "Bukayo Saka"], 0, "medium", "Manchester City midfielder."),
        ("Which manager led Blackburn Rovers to the 1994-95 Premier League title?", ["Kenny Dalglish", "Graeme Souness", "Roy Hodgson", "Mark Hughes"], 0, "medium", "Also won it as a player with Liverpool."),
        ("What nickname is given to West Ham United?", ["The Hammers", "The Eagles", "The Cherries", "The Clarets"], 0, "easy", "Reference to the club's heritage."),
        ("Which club did Mohamed Salah play for immediately before Liverpool?", ["Chelsea", "Fiorentina", "Roma", "Basel"], 2, "easy", "Italian club in Serie A."),
        ("Who scored a hat-trick on his Premier League debut for Manchester United in 1996?", ["Ole Gunnar Solskjaer", "Dwight Yorke", "Andy Cole", "Teddy Sheringham"], 0, "hard", "Against Blackburn Rovers."),
        ("Which stadium do Everton plan to move into from Goodison Park?", ["Bramley-Moore Dock", "Anfield", "Etihad Campus", "London Stadium"], 0, "hard", "New waterfront stadium project."),
        ("Who was the first £1 million player in English football?", ["Trevor Francis", "Bryan Robson", "Mark Hughes", "Paul Gascoigne"], 0, "hard", "Transferred to Nottingham Forest in 1979."),
        ("Which club did Riyad Mahrez win the Premier League with before Manchester City?", ["Leicester City", "Le Havre", "Queens Park Rangers", "Swansea City"], 0, "easy", "2015-16 surprise champions."),
        ("What is the capacity of the Emirates Stadium?", ["60,260", "62,850", "66,000", "74,000"], 0, "hard", "Arsenal's home since 2006."),
        ("Which player has the most red cards in Premier League history?", ["Patrick Vieira", "Richard Dunne", "Roy Keane", "Duncan Ferguson"], 1, "hard", "8 red cards."),
        ("Who managed Manchester City when they won their first Premier League title in 2011-12?", ["Mark Hughes", "Roberto Mancini", "Manuel Pellegrini", "Pep Guardiola"], 1, "medium", "Italian manager."),
        ("Which club is nicknamed 'The Cherries'?", ["Bournemouth", "Brentford", "Burnley", "Brighton"], 0, "easy", "Played at Dean Court / Vitality Stadium."),
        ("Who scored the winning goal for Manchester United in the 1999 Champions League final?", ["Teddy Sheringham", "Ole Gunnar Solskjaer", "Ryan Giggs", "David Beckham"], 1, "medium", "Injury-time winner in Barcelona."),
        ("Which team finished second to Leicester City in 2015-16?", ["Arsenal", "Tottenham Hotspur", "Manchester City", "Chelsea"], 1, "medium", "Spurs' best league finish in decades."),
        ("Who is the only player to score, assist, and score an own goal in one Premier League match?", ["Gareth Bale", "Ryan Shawcross", "Gareth Barry", "James Milner"], 1, "hard", "Stoke City vs Chelsea, 2012."),
        ("Which club did Declan Rice leave to join Arsenal in 2023?", ["Chelsea", "West Ham United", "Crystal Palace", "Brighton"], 1, "easy", "£105 million transfer."),
        ("Who won the Premier League Manager of the Season award in 2023-24?", ["Pep Guardiola", "Mikel Arteta", "Unai Emery", "Andoni Iraola"], 2, "medium", "Led Aston Villa to fourth place."),
        ("Which club plays at Selhurst Park?", ["Fulham", "Crystal Palace", "Watford", "Millwall"], 1, "easy", "South London club."),
        ("Who is Brighton manager who took them to the Europa League in 2023?", ["Graham Potter", "Roberto De Zerbi", "Chris Hughton", "Fabian Hurzeler"], 1, "medium", "Italian coach."),
        ("Which team won promotion to the Premier League in 2023 via the play-offs?", ["Sheffield United", "Luton Town", "Burnley", "Nottingham Forest"], 1, "medium", "Beat Coventry on penalties."),
    ],
    "la-liga": [
        ("Which club won La Liga in the 2023-24 season?", ["Real Madrid", "Barcelona", "Girona", "Atletico Madrid"], 0, "easy", "95 points under Carlo Ancelotti."),
        ("Who is Real Madrid's record signing as of 2024?", ["Gareth Bale", "Eden Hazard", "Jude Bellingham", "Cristiano Ronaldo"], 2, "medium", "Signed from Borussia Dortmund."),
        ("Which city hosts the Basque derby between Athletic Bilbao and Real Sociedad?", ["Bilbao", "San Sebastian", "Vitoria", "Pamplona"], 1, "hard", "Derby de la Realidad."),
        ("Who managed Barcelona when Lionel Messi made his first-team debut?", ["Frank Rijkaard", "Pep Guardiola", "Louis van Gaal", "Ronald Koeman"], 2, "hard", "Dutch manager in 2004."),
        ("Which club is nicknamed 'Los Granotes' (The Frogs)?", ["Getafe", "Levante", "Elche", "Valladolid"], 1, "medium", "Valencia-based club."),
        ("Who won the Pichichi Trophy in 2023-24?", ["Robert Lewandowski", "Artem Dovbyk", "Antoine Griezmann", "Jude Bellingham"], 1, "medium", "Girona striker with 24 goals."),
        ("Which stadium do Sevilla play their home matches at?", ["Benito Villamarin", "Ramon Sanchez Pizjuan", "La Cartuja", "Mestalla"], 1, "easy", "Famous for Europa League nights."),
        ("Who is the all-time top scorer for Atletico Madrid?", ["Luis Aragones", "Fernando Torres", "Antoine Griezmann", "Diego Costa"], 0, "hard", "172 goals for the club."),
        ("Which club did Xavi manage in La Liga?", ["Espanyol", "Barcelona", "Valencia", "Real Betis"], 1, "easy", "Returned to manage his boyhood club."),
        ("What year did Real Madrid sign Cristiano Ronaldo from Manchester United?", ["2007", "2009", "2011", "2013"], 1, "easy", "World record fee at the time."),
        ("Which team won the Copa del Rey in 2024?", ["Real Madrid", "Barcelona", "Athletic Bilbao", "Atletico Madrid"], 2, "medium", "Beat Mallorca in the final."),
        ("Who is Valencia's legendary former number 9 known as 'El Morbo'?", ["David Villa", "Mario Kempes", "Roberto Soldado", "Miguel Angel Angulo"], 0, "hard", "Top scorer for Spain in 2008 Euros."),
        ("Which La Liga club plays at the Benito Villamarin?", ["Betis", "Sevilla", "Cadiz", "Granada"], 0, "medium", "Green and white stripes in Seville."),
        ("Who scored a famous overhead kick for Real Madrid in the 2018 Champions League final?", ["Cristiano Ronaldo", "Gareth Bale", "Karim Benzema", "Marcelo"], 1, "easy", "Against Liverpool in Kyiv."),
        ("Which club did Luis Figo controversially join from Barcelona in 2000?", ["Valencia", "Real Madrid", "Atletico Madrid", "Deportivo"], 1, "easy", "The 'Pig's Head' transfer."),
        ("What is Girona's nickname?", ["Los Blanquivermells", "Los Franjiverdes", "Los Rojiblancos", "Los Azulgranas"], 0, "hard", "White and red colours."),
        ("Who is the youngest goalscorer in Real Madrid history?", ["Raul", "Vinicius Jr", "Lamine Yamal", "Rodrygo"], 3, "hard", "17 years old in 2019."),
        ("Which city do Celta Vigo play in?", ["Vigo", "La Coruna", "Oviedo", "Santander"], 0, "easy", "Galician port city."),
        ("Who managed Real Madrid during their 2021-22 Champions League and La Liga double?", ["Zinedine Zidane", "Carlo Ancelotti", "Julen Lopetegui", "Santiago Solari"], 1, "easy", "Fifth Champions League as manager."),
        ("Which club is based in the Canary Islands and has played in La Liga?", ["Las Palmas", "Tenerife", "Both of these", "Neither"], 2, "medium", "Both have had top-flight spells."),
        ("Who is Barcelona's current sporting director linked to many signings since 2021?", ["Mateu Alemany", "Deco", "Jordi Cruyff", "Eric Abidal"], 1, "medium", "Former Portuguese midfielder."),
        ("Which team plays at the Coliseum in Madrid suburb?", ["Getafe", "Leganes", "Rayo Vallecano", "Alcorcon"], 0, "medium", "South Madrid club."),
        ("Who won the Golden Shoe in Europe while playing for Atletico Madrid?", ["Diego Forlan", "Fernando Torres", "Luis Suarez", "Radamel Falcao"], 0, "hard", "2010-11 season."),
        ("Which club did Isco join after leaving Real Madrid?", ["Sevilla", "Real Betis", "Villarreal", "Getafe"], 1, "medium", "Andalusian club in 2023."),
        ("What is the capacity of Atletico Madrid's Metropolitano stadium?", ["54,000", "64,000", "68,456", "75,000"], 2, "hard", "Opened in 2017."),
        ("Which La Liga club is owned by former Newcastle player Michael Owen's business group?", ["None — trick question", "Racing Santander", "Malaga", "Almeria"], 0, "hard", "Ownership trivia curveball — Racing had various investors."),
        ("Who is Villarreal's long-serving manager known for Europa League success?", ["Unai Emery", "Marcelino", "Quique Sanchez Flores", "Manuel Pellegrini"], 0, "easy", "Won Europa League 2021."),
        ("Which player scored 50 goals in a calendar year for Barcelona in 2012?", ["Lionel Messi", "Samuel Eto'o", "David Villa", "Luis Suarez"], 0, "easy", "Record-breaking year."),
        ("Which club did Nico Williams play for before breaking through at Athletic Bilbao?", ["Athletic Bilbao youth", "Osasuna", "Real Sociedad", "Alaves"], 0, "easy", "One-club man from academy."),
        ("Which team won La Liga unbeaten in 2017-18?", ["Barcelona", "Real Madrid", "Atletico Madrid", "No team has done this"], 3, "medium", "Real came closest but lost twice."),
        ("Who is the all-time appearance leader for Real Madrid?", ["Iker Casillas", "Sergio Ramos", "Raul", "Manolo Sanchis"], 3, "hard", "702 appearances."),
        ("Which city hosts the Seville derby between Sevilla and Real Betis?", ["Seville", "Malaga", "Cordoba", "Granada"], 0, "easy", "Derbi sevillano."),
    ],
    "ucl": [
        ("Which club won the 2024 Champions League final?", ["Manchester City", "Real Madrid", "Borussia Dortmund", "Bayern Munich"], 1, "easy", "2-0 at Wembley."),
        ("Who scored twice for Real Madrid in the 2024 UCL final?", ["Vinicius Jr", "Rodrygo", "Jude Bellingham", "Karim Benzema"], 0, "easy", "Brazilian winger."),
        ("Which stadium hosted the 2023 Champions League final?", ["Wembley", "Ataturk Olympic Stadium", "Allianz Arena", "Stade de France"], 1, "medium", "Istanbul."),
        ("Who scored in the 2014, 2018, and 2022 Champions League finals for Real Madrid?", ["Cristiano Ronaldo", "Karim Benzema", "Gareth Bale", "Raul"], 1, "hard", "French striker for Los Blancos."),
        ("Which club did Porto beat in the 2004 Champions League final?", ["Monaco", "Chelsea", "Deportivo", "Milan"], 0, "medium", "3-0 under Jose Mourinho."),
        ("Who holds the record for most Champions League appearances?", ["Iker Casillas", "Cristiano Ronaldo", "Lionel Messi", "Xavi"], 0, "hard", "177 appearances."),
        ("Which team completed a treble including the Champions League in 2023?", ["Real Madrid", "Manchester City", "Inter Milan", "Bayern Munich"], 1, "easy", "First English treble since 1999."),
        ("Who scored the winning penalty for Chelsea in the 2012 final shootout?", ["Frank Lampard", "Didier Drogba", "Juan Mata", "Ashley Cole"], 1, "easy", "Against Bayern Munich."),
        ("Which club has lost the most Champions League finals?", ["Juventus", "Benfica", "Atletico Madrid", "Bayern Munich"], 0, "hard", "Seven final defeats."),
        ("Who managed Ajax to the 1995 Champions League title?", ["Louis van Gaal", "Frank Rijkaard", "Danny Blind", "Marco van Basten"], 0, "medium", "Beat AC Milan in Vienna."),
        ("Which player scored twice as a substitute for Real Madrid in the 2018 Champions League final?", ["Karim Benzema", "Gareth Bale", "Cristiano Ronaldo", "Isco"], 1, "hard", "Welsh winger off the bench."),
        ("What was the original name of the Champions League trophy?", ["European Champion Clubs' Cup", "Henri Delaunay Trophy", "UEFA Cup", "Coupe des Clubs"], 0, "hard", "The 'big ears' trophy."),
        ("Which club did AC Milan beat in the 2007 Champions League final?", ["Liverpool", "Arsenal", "Chelsea", "Manchester United"], 0, "medium", "2-1 in Athens."),
        ("Who is the youngest Champions League goalscorer?", ["Ansu Fati", "Lamine Yamal", "Cesc Fabregas", "Bojan Krkic"], 3, "medium", "17 years and 22 days for Barcelona."),
        ("Which team won the Champions League in 2005 after being 3-0 down?", ["AC Milan", "Liverpool", "Chelsea", "Juventus"], 1, "easy", "Miracle of Istanbul."),
        ("Who scored the fastest hat-trick in Champions League history?", ["Robert Lewandowski", "Cristiano Ronaldo", "Lionel Messi", "Marco Simone"], 0, "hard", "3 goals in 4 minutes vs Real Madrid."),
        ("Which club won the first Champions League season in 1992-93?", ["Barcelona", "Marseille", "AC Milan", "Ajax"], 1, "medium", "Beat AC Milan 1-0."),
        ("Who managed Real Madrid to three consecutive UCL titles 2016-18?", ["Carlo Ancelotti", "Zinedine Zidane", "Rafael Benitez", "Jose Mourinho"], 1, "easy", "French legend."),
        ("Which player has scored in the most different Champions League seasons?", ["Cristiano Ronaldo", "Lionel Messi", "Karim Benzema", "Robert Lewandowski"], 0, "hard", "20 consecutive seasons."),
        ("Which club did Borussia Dortmund beat in the 1997 Champions League final?", ["Juventus", "Ajax", "Manchester United", "Real Madrid"], 0, "hard", "3-1 in Munich."),
        ("Who won the Champions League with three different clubs as a player?", ["Samuel Eto'o", "Clarence Seedorf", "Both of these", "Neither"], 2, "hard", "Both achieved this feat."),
        ("Which stadium is known for hosting the most Champions League finals?", ["Wembley", "San Siro", "Stade de France", "Camp Nou"], 0, "hard", "Hosted eight finals."),
        ("Who scored the only goal in the 2010 Inter Milan Champions League final win?", ["Wesley Sneijder", "Diego Milito", "Samuel Eto'o", "Goran Pandev"], 1, "medium", "Beat Bayern Munich 2-0."),
        ("Which club did Manchester United beat in the 2008 Champions League final?", ["Barcelona", "Chelsea", "Liverpool", "Arsenal"], 1, "easy", "Penalty shootout in Moscow."),
        ("Who is the all-time top assist provider in Champions League history?", ["Lionel Messi", "Cristiano Ronaldo", "Ryan Giggs", "Angel Di Maria"], 1, "hard", "Same as top scorer record holder."),
        ("Which team won the Champions League without losing a single match in 2019-20?", ["Bayern Munich", "Paris Saint-Germain", "Liverpool", "Real Madrid"], 0, "medium", "Won every game in the tournament."),
        ("Who managed Liverpool to the 2019 Champions League title?", ["Rafael Benitez", "Brendan Rodgers", "Jurgen Klopp", "Kenny Dalglish"], 2, "easy", "Beat Tottenham 2-0 in Madrid."),
        ("Which club has appeared in the most Champions League semi-finals?", ["Real Madrid", "Barcelona", "Bayern Munich", "AC Milan"], 0, "hard", "Over 30 semi-final appearances."),
        ("Who scored the winning goal for Manchester United in the 1999 Champions League final?", ["Teddy Sheringham", "Ole Gunnar Solskjaer", "David Beckham", "Ryan Giggs"], 1, "easy", "Injury time in Barcelona."),
        ("Which club did Real Madrid beat in the 2022 Champions League final?", ["Manchester City", "Liverpool", "Chelsea", "Bayern Munich"], 1, "easy", "1-0 in Paris, Vinicius scored."),
        ("Who won the Champions League Golden Boot in 2023-24?", ["Erling Haaland", "Kylian Mbappe", "Harry Kane", "Jude Bellingham"], 1, "medium", "8 goals despite PSG exit."),
        ("Which player has the most Champions League winner's medals?", ["Francisco Gento", "Paolo Maldini", "Cristiano Ronaldo", "Luka Modric"], 0, "hard", "Six with Real Madrid 1950s-60s."),
        ("Which club did Chelsea beat on penalties in the 2021 Champions League final?", ["Bayern Munich", "Manchester City", "Real Madrid", "Paris Saint-Germain"], 1, "medium", "Kai Havertz scored the winner."),
        ("Who managed Bayern Munich to the 2020 Champions League title?", ["Pep Guardiola", "Hansi Flick", "Julian Nagelsmann", "Jupp Heynckes"], 1, "medium", "Beat PSG 1-0 in Lisbon."),
        ("Which team is the only one to win the Champions League after qualifying through a play-off round?", ["Liverpool", "Manchester United", "Red Star Belgrade", "No team has"], 0, "hard", "2005 champions."),
    ],
    "world-cup": [
        ("Which country will co-host the 2026 FIFA World Cup?", ["USA, Mexico & Canada", "USA only", "Mexico & USA", "Canada & USA"], 0, "easy", "First 48-team tournament."),
        ("Who won the Golden Ball at the 2022 World Cup?", ["Kylian Mbappe", "Lionel Messi", "Luka Modric", "Emiliano Martinez"], 1, "easy", "Argentina captain."),
        ("Which country hosted the 2010 FIFA World Cup?", ["Nigeria", "South Africa", "Egypt", "Morocco"], 1, "easy", "First African host."),
        ("Who is the all-time top scorer in World Cup qualifying matches?", ["Cristiano Ronaldo", "Ali Daei", "Lionel Messi", "Pele"], 1, "hard", "Iranian striker."),
        ("Which team won the 1954 World Cup final known as the 'Miracle of Bern'?", ["Hungary", "West Germany", "Brazil", "Uruguay"], 1, "hard", "Beat Hungary 3-2."),
        ("Who scored the 'Goal of the Century' at the 1986 World Cup?", ["Diego Maradona", "Jorge Valdano", "Gary Lineker", "Emilio Butragueno"], 0, "easy", "Against England."),
        ("Which country has the most World Cup semi-final appearances?", ["Brazil", "Germany", "Italy", "Argentina"], 1, "medium", "13 semi-finals."),
        ("Who won the 2002 World Cup Golden Boot?", ["Ronaldo", "Miroslav Klose", "Rivaldo", "David Beckham"], 0, "medium", "8 goals for Brazil."),
        ("Which nation won the first Women's World Cup in 1991?", ["Norway", "USA", "Germany", "Sweden"], 1, "medium", "Beat Norway in the final."),
        ("Who managed Argentina to the 2022 World Cup title?", ["Lionel Scaloni", "Jorge Sampaoli", "Alejandro Sabella", "Diego Maradona"], 0, "easy", "Former player, first major trophy as coach."),
        ("Which country hosted the 2006 FIFA World Cup?", ["France", "Germany", "Italy", "Spain"], 1, "easy", "Italy won the tournament."),
        ("Who scored a hat-trick in the 2022 World Cup final?", ["Lionel Messi", "Kylian Mbappe", "Julian Alvarez", "Gonzalo Montiel"], 1, "easy", "France striker, still lost."),
        ("Which team won the 1970 World Cup in Mexico?", ["Italy", "Brazil", "West Germany", "Uruguay"], 1, "easy", "Pele's third World Cup."),
        ("Who is the oldest goalscorer in World Cup history?", ["Roger Milla", "Cristiano Ronaldo", "Gyan", "Pepe"], 0, "hard", "42 years old for Cameroon in 1994."),
        ("Which country did Croatia beat to finish third in 2022?", ["Morocco", "France", "Brazil", "Netherlands"], 0, "easy", "2-1 in the third-place play-off."),
        ("Who won the Golden Glove at the 2018 World Cup?", ["Thibaut Courtois", "Jordan Pickford", "Hugo Lloris", "Danijel Subasic"], 0, "medium", "Belgium goalkeeper."),
        ("Which nation has never failed to qualify for a World Cup?", ["Germany", "Brazil", "Argentina", "Italy"], 1, "easy", "Every tournament since 1930."),
        ("Who scored the winning goal in the 2014 World Cup final?", ["Thomas Muller", "Mario Gotze", "Andre Schurrle", "Miroslav Klose"], 1, "easy", "Extra time vs Argentina."),
        ("Which country hosted the 1994 FIFA World Cup?", ["Mexico", "USA", "Brazil", "Argentina"], 1, "medium", "Brazil won the final."),
        ("Who is the only player to score in five World Cups?", ["Pele", "Miroslav Klose", "Cristiano Ronaldo", "Lionel Messi"], 2, "medium", "2006 through 2022."),
        ("Which team won the 1966 World Cup on home soil?", ["West Germany", "England", "Portugal", "Soviet Union"], 1, "easy", "Beat West Germany 4-2."),
        ("Who managed France to the 2018 World Cup title?", ["Didier Deschamps", "Laurent Blanc", "Raymond Domenech", "Roger Lemerre"], 0, "easy", "Also won as a player in 1998."),
        ("Which country did Senegal beat in the opening match of the 2022 World Cup?", ["Qatar", "Netherlands", "Ecuador", "Iran"], 0, "medium", "2-1 upset."),
        ("Who won the Golden Boot at the 2014 World Cup?", ["Thomas Muller", "James Rodriguez", "Neymar", "Robin van Persie"], 1, "medium", "Colombia playmaker, 6 goals."),
        ("Which nation has won the most Women's World Cups?", ["Germany", "USA", "Norway", "Japan"], 1, "easy", "Four titles."),
        ("Who scored the 'Hand of God' goal at the 1986 World Cup?", ["Jorge Valdano", "Diego Maradona", "Peter Shilton", "Gary Lineker"], 1, "easy", "Argentina vs England."),
        ("Which country hosted the 2018 FIFA World Cup?", ["Ukraine", "Russia", "Poland", "Turkey"], 1, "easy", "France won the tournament."),
        ("Who is the youngest captain to lift the World Cup trophy?", ["Diego Maradona", "Pele", "Carlos Alberto", "Franz Beckenbauer"], 1, "hard", "17 years old in 1958."),
        ("Which team did Italy beat on penalties in the 2006 World Cup final?", ["Brazil", "Germany", "France", "Argentina"], 2, "easy", "Zidane sent off in Berlin."),
        ("Who won the Golden Ball at the 2018 World Cup?", ["Kylian Mbappe", "Luka Modric", "Harry Kane", "Antoine Griezmann"], 1, "medium", "Croatia midfielder."),
        ("Which country has hosted the World Cup the most times?", ["Germany", "Mexico", "Italy", "France"], 1, "medium", "1970 and 1986."),
        ("Who scored the fastest hat-trick in World Cup history?", ["Geoff Hurst", "Gabriel Batistuta", "Ernst Wilimowski", "Just Fontaine"], 1, "hard", "3 goals in 11 minutes for Argentina vs Greece 1998."),
        ("Which nation won the 1998 World Cup on home soil?", ["Brazil", "France", "Croatia", "Netherlands"], 1, "easy", "3-0 vs Brazil in Paris."),
        ("Who is the all-time top scorer for the US men's national team?", ["Clint Dempsey", "Landon Donovan", "Christian Pulisic", "Jozy Altidore"], 1, "medium", "57 international goals."),
        ("Which country did Morocco beat to reach the 2022 World Cup semi-final?", ["Spain", "Portugal", "Belgium", "Croatia"], 1, "easy", "1-0 quarter-final victory."),
    ],
    "daily": [
        ("Which club is nicknamed 'The Blues' in London?", ["Arsenal", "Chelsea", "West Ham", "Tottenham"], 1, "easy", "Play at Stamford Bridge."),
        ("Erling Haaland was born in which country?", ["Norway", "Sweden", "Denmark", "Iceland"], 0, "easy", "Son of Alf-Inge Haaland."),
        ("Which country does Vinicius Jr represent?", ["Spain", "Brazil", "Portugal", "Argentina"], 1, "easy", "Real Madrid winger."),
        ("What position does Manuel Neuer play?", ["Defender", "Midfielder", "Striker", "Goalkeeper"], 3, "easy", "Bayern Munich captain."),
        ("Which club does Bukayo Saka play for?", ["Chelsea", "Arsenal", "Tottenham", "West Ham"], 1, "easy", "England international."),
        ("How long is a standard football match excluding stoppage time?", ["80 minutes", "90 minutes", "100 minutes", "120 minutes"], 1, "easy", "Two 45-minute halves."),
        ("Which country does Luka Modric represent?", ["Serbia", "Croatia", "Slovenia", "Bosnia"], 1, "easy", "2018 Ballon d'Or winner."),
        ("Who is the manager of Liverpool as of 2024?", ["Jurgen Klopp", "Arne Slot", "Xabi Alonso", "Ruben Amorim"], 1, "medium", "Replaced Klopp in 2024."),
        ("Which club plays at the San Siro?", ["Juventus", "AC Milan & Inter", "Roma", "Napoli"], 1, "easy", "Shared stadium in Milan."),
        ("What colour cards can a referee show?", ["Red and Blue", "Yellow and Red", "Green and Yellow", "White and Red"], 1, "easy", "Two caution levels."),
        ("Which nation does Son Heung-min represent?", ["Japan", "South Korea", "China", "North Korea"], 1, "easy", "Tottenham forward."),
        ("Who won the 2020 UEFA European Championship?", ["England", "Italy", "Spain", "France"], 1, "medium", "Beat England on penalties."),
        ("Which club is nicknamed 'The Old Lady'?", ["AC Milan", "Juventus", "Inter Milan", "Roma"], 1, "easy", "Italian giants from Turin."),
        ("What is the maximum number of substitutions allowed in most competitions now?", ["3", "4", "5", "6"], 2, "medium", "Increased after COVID-19 rules."),
        ("Which country does Pedri represent?", ["Portugal", "Spain", "Brazil", "Argentina"], 1, "easy", "Barcelona midfielder."),
        ("Who is the captain of Belgium's national team traditionally associated with number 10?", ["Romelu Lukaku", "Kevin De Bruyne", "Eden Hazard", "Axel Witsel"], 1, "medium", "Manchester City playmaker."),
        ("Which club did Cristiano Ronaldo join after Manchester United in 2009?", ["Barcelona", "Real Madrid", "Juventus", "PSG"], 1, "easy", "Spanish giants."),
        ("How many players must a team have on the pitch to continue a match?", ["9", "10", "11", "7"], 3, "medium", "Minimum to avoid abandonment."),
        ("Which country does Khvicha Kvaratskhelia represent?", ["Georgia", "Armenia", "Azerbaijan", "Ukraine"], 0, "medium", "Napoli/PSG winger."),
        ("Who won the FIFA Club World Cup in 2023?", ["Real Madrid", "Manchester City", "Fluminense", "Chelsea"], 1, "medium", "Beat Fluminense in final."),
        ("Which club is based in Turin and wears black and white stripes?", ["Torino", "Juventus", "Atalanta", "Genoa"], 1, "easy", "Most successful Italian club."),
        ("What does VAR stand for in football?", ["Video Assistant Referee", "Virtual Action Review", "Verified Assistant Rules", "Video Action Replay"], 0, "easy", "Technology for reviewing decisions."),
        ("Which country does Alphonso Davies represent?", ["USA", "Canada", "Jamaica", "Liberia"], 1, "easy", "Bayern Munich left-back."),
        ("Who is known as 'The Special One' in football management?", ["Pep Guardiola", "Jose Mourinho", "Carlo Ancelotti", "Jurgen Klopp"], 1, "easy", "Self-given nickname at Chelsea."),
        ("Which club plays at Anfield?", ["Everton", "Liverpool", "Manchester United", "Leeds United"], 1, "easy", "You'll Never Walk Alone."),
        ("What is the offside rule triggered by?", ["Foul play", "Being ahead of the second-last defender", "Handball", "Dangerous play"], 1, "medium", "When the ball is played to you."),
        ("Which country does Jamal Musiala represent?", ["England", "Germany", "Poland", "Ghana"], 1, "medium", "Bayern Munich attacking midfielder."),
        ("Who won the 2016 UEFA European Championship?", ["France", "Portugal", "Germany", "Wales"], 1, "medium", "Eder scored the winner."),
        ("Which club is nicknamed 'The Citizens'?", ["Manchester United", "Manchester City", "Leicester City", "Bristol City"], 1, "easy", "Manchester sky blue club."),
        ("What is the standard width of a football goal in metres?", ["5.5m", "7.32m", "8m", "6m"], 1, "hard", "Regulation goal size."),
        ("Which country does Rafael Leao represent?", ["Brazil", "Portugal", "Angola", "France"], 1, "easy", "AC Milan winger."),
        ("Who managed Spain to the 2010 World Cup title?", ["Luis Aragones", "Vicente del Bosque", "Julen Lopetegui", "Luis Enrique"], 1, "easy", "Also won Euro 2012."),
        ("Which club did N'Golo Kante join after Leicester City?", ["Arsenal", "Chelsea", "Manchester United", "Tottenham"], 1, "easy", "Won Premier League with both clubs."),
        ("What is a hat-trick in football?", ["Three assists", "Three goals in one match", "Three clean sheets", "Three yellow cards"], 1, "easy", "Scoring three goals."),
        ("Which country does Victor Osimhen represent?", ["Ghana", "Nigeria", "Cameroon", "Senegal"], 1, "easy", "Napoli/Galatasaray striker."),
    ],
    "bundesliga": [
        ("Who managed Bayer Leverkusen during their unbeaten 2023-24 season?", ["Julian Nagelsmann", "Xabi Alonso", "Thomas Tuchel", "Edin Terzic"], 1, "easy", "Former Real Madrid midfielder."),
        ("Which club has the famous 'Yellow Wall' terrace?", ["Bayern Munich", "Borussia Dortmund", "Schalke 04", "RB Leipzig"], 1, "easy", "Signal Iduna Park south stand."),
        ("Who is Bayern Munich's all-time leading goalscorer?", ["Gerd Muller", "Robert Lewandowski", "Thomas Muller", "Roland Wohlfarth"], 1, "medium", "344 goals for the club."),
        ("Which city do RB Leipzig play in?", ["Dresden", "Leipzig", "Halle", "Chemnitz"], 1, "easy", "East German city."),
        ("Who won the Bundesliga Golden Boot in 2023-24?", ["Harry Kane", "Serhou Guirassy", "Lois Openda", "Thomas Muller"], 0, "easy", "36 goals for Bayern."),
        ("Which club is nicknamed 'Die Roten'?", ["Bayern Munich", "Bayer Leverkusen", "Eintracht Frankfurt", "Mainz 05"], 0, "easy", "The Reds in Bavaria."),
        ("Who is the longest-serving player at Borussia Dortmund historically?", ["Marco Reus", "Michael Zorc", "Roman Weidenfeller", "Mats Hummels"], 1, "hard", "Over 500 appearances."),
        ("Which stadium do Eintracht Frankfurt play at?", ["Commerzbank-Arena / Deutsche Bank Park", "Olympiastadion", "RheinEnergieStadion", "WWK Arena"], 0, "medium", "Frankfurt's home ground."),
        ("Who scored 5 goals in 9 minutes for Bayern against Wolfsburg in 2015?", ["Thomas Muller", "Robert Lewandowski", "Mario Mandzukic", "Arjen Robben"], 1, "easy", "Legendary substitute performance."),
        ("Which club did Jurgen Klopp manage before Liverpool?", ["Bayer Leverkusen", "Borussia Dortmund", "Mainz 05", "Schalke 04"], 1, "easy", "Won two Bundesliga titles."),
        ("What is the capacity of Borussia Dortmund's Signal Iduna Park?", ["65,000", "75,000", "81,365", "90,000"], 2, "hard", "Largest stadium in Germany."),
        ("Which team won the Bundesliga in 2001-02?", ["Bayern Munich", "Borussia Dortmund", "Bayer Leverkusen", "Werder Bremen"], 1, "hard", "Last title before Bayern dominance."),
        ("Who is Freiburg's long-serving manager known for overachievement?", ["Christian Streich", "Dieter Hecking", "Markus Weinzierl", "Stefan Kuntz"], 0, "medium", "Managed club for over a decade."),
        ("Which club is based in Gelsenkirchen?", ["Borussia Dortmund", "Schalke 04", "Bochum", "Duisburg"], 1, "easy", "Royal Blues."),
        ("Who won the Bundesliga with Wolfsburg in 2008-09?", ["Felix Magath", "Jupp Heynckes", "Louis van Gaal", "Thomas Schaaf"], 0, "hard", "Edin Dzeko top scorer."),
        ("Which player is known as 'Muller' or 'Raumdeuter' at Bayern?", ["Thomas Muller", "Gerd Muller", "Joshua Kimmich", "Manuel Neuer"], 0, "easy", "Space interpreter."),
        ("What year was the Bundesliga founded?", ["1960", "1963", "1965", "1970"], 1, "medium", "Replaced Oberliga system."),
        ("Which club did Toni Kroos play for before Real Madrid?", ["Bayer Leverkusen", "Bayern Munich", "Borussia Dortmund", "Stuttgart"], 1, "easy", "Bayern then loan at Leverkusen."),
        ("Who is Hoffenheim's financial backer that caused controversy?", ["Red Bull", "SAP / Dietmar Hopp", "Volkswagen", "Adidas"], 1, "hard", "Software billionaire owner."),
        ("Which team plays at the Volksparkstadion?", ["St Pauli", "Hamburger SV", "Hannover 96", "Werder Bremen"], 1, "medium", "Historic Hamburg club."),
        ("Who managed Bayern to the sextuple in 2020?", ["Pep Guardiola", "Hansi Flick", "Niko Kovac", "Louis van Gaal"], 1, "medium", "Treble plus Club World Cup and Super Cup."),
        ("Which club is nicknamed 'Die Werderaner'?", ["Werder Bremen", "Hamburg SV", "St Pauli", "Holstein Kiel"], 0, "medium", "River island club."),
        ("Who is the youngest Bundesliga goalscorer?", ["Youssoufa Moukoko", "Jamal Musiala", "Nuri Sahin", "Florian Wirtz"], 0, "medium", "16 years 28 days."),
        ("Which city do Bayer Leverkusen represent?", ["Munich", "Leverkusen", "Cologne", "Dusseldorf"], 1, "easy", "Pharmaceutical company town."),
        ("Who won the Bundesliga Fair Play award most often?", ["Bayern Munich", "Freiburg", "Mainz 05", "No single record"], 3, "hard", "Varies by season."),
        ("Which club did Robert Lewandowski join Bayern from?", ["Dortmund", "Lech Poznan", "Borussia Dortmund", "Both A and C"], 3, "easy", "2014 free transfer from BVB."),
        ("What is the Revierderby contested between?", ["Bayern and Dortmund", "Schalke and Dortmund", "Cologne and Leverkusen", "Frankfurt and Mainz"], 1, "easy", "Ruhr area rivalry."),
        ("Who is VfB Stuttgart's famous youth graduate who joined Bayern?", ["Mario Gomez", "Sami Khedira", "Timo Werner", "All of these"], 3, "hard", "All came through Stuttgart academy."),
        ("Which club plays at the Red Bull Arena?", ["Bayern Munich", "RB Leipzig", "Hoffenheim", "Augsburg"], 1, "easy", "Leipzig's home."),
        ("Who managed Borussia Dortmund to back-to-back Bundesliga titles 2010-12?", ["Thomas Tuchel", "Jurgen Klopp", "Lucien Favre", "Edin Terzic"], 1, "easy", "Before moving to Liverpool."),
        ("Which team was promoted to Bundesliga in 2023-24 alongside Darmstadt?", ["Heidenheim", "Hamburg", "Kiel", "St Pauli"], 0, "medium", "First ever Bundesliga season."),
        ("Who is Bayern's record signing as of 2024?", ["Lucas Hernandez", "Harry Kane", "Matthijs de Ligt", "Leroy Sane"], 1, "medium", "From Tottenham Hotspur."),
        ("Which club is known as 'FC Hollywood'?", ["Borussia Dortmund", "Bayern Munich", "Hamburger SV", "Cologne"], 1, "medium", "Media scrutiny nickname."),
        ("Who scored the winning goal for Germany in the 2014 World Cup final?", ["Mario Gotze", "Thomas Muller", "Andre Schurrle", "Mesut Ozil"], 0, "easy", "Bayern-connected player."),
        ("Which Bundesliga club is based in Augsburg?", ["FC Augsburg", "Augsburg 1907", "SpVgg Unterhaching", "1860 Munich"], 0, "easy", "FCA in Bavaria."),
    ],
    "serie-a": [
        ("Who won the Serie A title in 2023-24?", ["Juventus", "Inter Milan", "AC Milan", "Napoli"], 1, "easy", "Second star on shirt."),
        ("Which club is nicknamed 'I Partenopei'?", ["Roma", "Napoli", "Palermo", "Cagliari"], 1, "medium", "Named after Greek founders of Naples."),
        ("Who is AC Milan's all-time leading goalscorer?", ["Gianni Rivera", "Gunnar Nordahl", "Filippo Inzaghi", "Andriy Shevchenko"], 1, "hard", "Swedish striker, 221 goals."),
        ("Which stadium do Napoli play at?", ["Stadio Olimpico", "Stadio Diego Armando Maradona", "San Siro", "Artemio Franchi"], 1, "easy", "Named after club legend."),
        ("Who managed Inter Milan to the 2023-24 Serie A title?", ["Antonio Conte", "Simone Inzaghi", "Stefano Pioli", "Jose Mourinho"], 1, "easy", "Brother of Filippo Inzaghi."),
        ("Which club is nicknamed 'La Dea' (The Goddess)?", ["Atalanta", "Fiorentina", "Lazio", "Sampdoria"], 0, "medium", "Bergamo club."),
        ("Who is Juventus' all-time leading appearance maker?", ["Gianluigi Buffon", "Alessandro Del Piero", "Giorgio Chiellini", "Gianluca Pessotto"], 0, "medium", "657 appearances."),
        ("Which city hosts the Derby della Madonnina?", ["Rome", "Milan", "Turin", "Genoa"], 1, "easy", "AC Milan vs Inter."),
        ("Who won the Serie A Golden Boot in 2023-24?", ["Lautaro Martinez", "Dusan Vlahovic", "Victor Osimhen", "Olivier Giroud"], 0, "medium", "24 goals for Inter."),
        ("Which club did Cristiano Ronaldo play for in Serie A?", ["AC Milan", "Inter Milan", "Juventus", "Roma"], 2, "easy", "2018-2021."),
        ("What is the name of Roma's passionate fan group?", ["Curva Sud", "Curva Nord", "Ultras Lazio", "Fossa dei Leoni"], 0, "hard", "South curve ultras."),
        ("Who managed Juventus during their nine consecutive Scudetti 2011-20?", ["Antonio Conte", "Massimiliano Allegri", "Andrea Pirlo", "Maurizio Sarri"], 1, "medium", "Two spells as manager."),
        ("Which club is based in Bergamo?", ["Atalanta", "Brescia", "Como", "Cremonese"], 0, "easy", "Regular Champions League qualifiers."),
        ("Who is known as 'Il Fenomeno' in Italian football history?", ["Roberto Baggio", "Ronaldo Nazario", "Francesco Totti", "Paolo Maldini"], 1, "medium", "Brazilian striker at Inter and Milan."),
        ("Which team plays at the Stadio Renato Dall'Ara?", ["Parma", "Bologna", "Udinese", "Verona"], 1, "medium", "Emilia-Romagna club."),
        ("Who scored the winning penalty for Italy in the Euro 2020 final?", ["Jorginho", "Gianluigi Donnarumma", "Leonardo Bonucci", "Federico Chiesa"], 1, "medium", "Saved two penalties too."),
        ("Which club is nicknamed 'I Giallorossi'?", ["Roma", "Lazio", "Lecce", "Frosinone"], 0, "easy", "Yellow and reds."),
        ("Who is the youngest Serie A goalscorer?", ["Amedeo Amadei", "Moise Kean", "Pietro Pellegri", "Lamine Yamal"], 0, "hard", "16 years 1 month in 1937."),
        ("Which city hosts the Derby della Lanterna?", ["Milan", "Genoa", "Turin", "Bologna"], 1, "medium", "Genoa vs Sampdoria."),
        ("Who managed AC Milan to the 2021-22 Serie A title?", ["Carlo Ancelotti", "Stefano Pioli", "Marco Giampaolo", "Gennaro Gattuso"], 1, "medium", "Ended Juventus dominance briefly."),
        ("Which club did Zlatan Ibrahimovic play for in Serie A?", ["Juventus, Inter, and AC Milan", "Only AC Milan", "Only Inter", "Roma and Lazio"], 0, "medium", "Three of Italy's biggest clubs."),
        ("What is the capacity of San Siro?", ["65,000", "75,817", "80,000", "90,000"], 1, "hard", "Shared by Milan and Inter."),
        ("Who is known as 'Il Capitano' at Roma?", ["Daniele De Rossi", "Francesco Totti", "Aldair", "Bruno Conti"], 1, "easy", "One-club legend."),
        ("Which club won the Serie A title in 1984-85?", ["Juventus", "Hellas Verona", "Torino", "Como"], 1, "hard", "Only Scudetto in club history."),
        ("Who is Inter Milan's record signing as of 2024?", ["Romelu Lukaku", "Lautaro Martinez", "Marcus Thuram", "Christian Vieri"], 0, "medium", "£97m from Manchester United."),
        ("Which club is nicknamed 'I Biancocelesti'?", ["Lazio", "Napoli", "Atalanta", "Empoli"], 0, "easy", "White and sky blue."),
        ("Who managed Napoli to their 2022-23 Serie A title?", ["Rafael Benitez", "Luciano Spalletti", "Carlo Ancelotti", "Maurizio Sarri"], 1, "easy", "First Scudetto since Maradona era."),
        ("Which player is known as 'Il Divin Codino'?", ["Roberto Baggio", "Alessandro Del Piero", "Gianfranco Zola", "Francesco Totti"], 0, "medium", "Famous ponytail."),
        ("Which club plays at the Stadio Artemio Franchi?", ["Fiorentina", "Siena", "Livorno", "Pisa"], 0, "medium", "Florence club."),
        ("Who won the Ballon d'Or while playing in Serie A in 2003?", ["Paolo Maldini", "Pavel Nedved", "Andriy Shevchenko", "Ronaldinho"], 1, "hard", "Juventus midfielder."),
        ("Which team is based in Turin alongside Juventus?", ["Torino", "Cremonese", "Parma", "Spezia"], 0, "easy", "Derby della Mole."),
        ("Who is the all-time top scorer for Inter Milan?", ["Giuseppe Meazza", "Ronaldo", "Samuel Eto'o", "Mauro Icardi"], 0, "hard", "Stadium named after him."),
        ("Which club did Paulo Dybala join after leaving Juventus?", ["Inter Milan", "Roma", "Napoli", "Lazio"], 1, "medium", "2022 free transfer."),
        ("Who managed Italy to the 2006 World Cup title?", ["Giovanni Trapattoni", "Marcello Lippi", "Roberto Mancini", "Antonio Conte"], 1, "easy", "Beat France on penalties."),
        ("Which Serie A club is nicknamed 'I Rossoblu'?", ["Cagliari", "Genoa", "Atalanta", "Multiple clubs share this"], 3, "hard", "Genoa, Cagliari, and others use red-blue."),
    ],
    "ligue-1": [
        ("Who won the Ligue 1 title in 2023-24?", ["Monaco", "Paris Saint-Germain", "Brest", "Nice"], 1, "easy", "PSG's 12th title."),
        ("Which club is nicknamed 'Les Aiglons'?", ["Nice", "Monaco", "Lyon", "Lille"], 1, "medium", "The Eagles of Monaco."),
        ("Who is Marseille's all-time leading goalscorer?", ["Jean-Pierre Papin", "Mickael Cantona", "Didier Drogba", "Andre-Pierre Gignac"], 0, "hard", "134 goals."),
        ("Which stadium do Lyon play at?", ["Stade Velodrome", "Groupama Stadium", "Parc OL", "Stade Geoffroy-Guichard"], 2, "easy", "Also called Groupama Stadium."),
        ("Who managed PSG to their first Champions League final in 2020?", ["Unai Emery", "Thomas Tuchel", "Mauricio Pochettino", "Christophe Galtier"], 1, "medium", "Lost 1-0 to Bayern."),
        ("Which club is nicknamed 'Les Canaris'?", ["Nantes", "Lorient", "Toulouse", "Brest"], 0, "medium", "The Canaries, yellow and green."),
        ("Who is the youngest Ligue 1 goalscorer?", ["Kylian Mbappe", "Maurice Burlut", "Anthony Martial", "Warren Zaire-Emery"], 0, "hard", "17 years 2 months."),
        ("Which city hosts Le Classique?", ["Lyon", "Paris & Marseille", "Lille & Lens", "Nice & Monaco"], 1, "easy", "PSG vs Marseille."),
        ("Who won the Ligue 1 Golden Boot in 2023-24?", ["Kylian Mbappe", "Jonathan David", "Alexandre Lacazette", "Pierre-Emerick Aubameyang"], 0, "easy", "27 goals."),
        ("Which club did Neymar join in Ligue 1?", ["Monaco", "Paris Saint-Germain", "Marseille", "Lyon"], 1, "easy", "World record transfer from Barcelona."),
        ("What is the capacity of Stade Velodrome?", ["55,000", "67,394", "75,000", "80,000"], 1, "hard", "Marseille's home."),
        ("Who managed Monaco to the 2016-17 Ligue 1 title?", ["Leonardo Jardim", "Thierry Henry", "Didier Deschamps", "Claudio Ranieri"], 0, "medium", "Beat PSG to the title."),
        ("Which club is based in Lens?", ["RC Lens", "Lille OSC", "Amiens", "Valenciennes"], 0, "easy", "Sang et Or."),
        ("Who is known as 'Le President' in French football culture?", ["Jean-Michel Aulas", "Nasser Al-Khelaifi", "Bernard Tapie", "Michel Hidalgo"], 0, "hard", "Long-time Lyon president."),
        ("Which team plays at Stade de la Beaujoire?", ["Rennes", "Nantes", "Guingamp", "Lorient"], 1, "medium", "Nantes' home ground."),
        ("Who scored the winning goal for France in the 1998 World Cup final?", ["Zinedine Zidane", "Emmanuel Petit", "Youri Djorkaeff", "Thierry Henry"], 1, "medium", "Third goal vs Brazil."),
        ("Which club is nicknamed 'Le Stade Malherbe'?", ["Caen", "Troyes", "Auxerre", "Sochaux"], 0, "hard", "Normandy club."),
        ("Who is PSG's sporting director linked to many transfers since 2011?", ["Leonardo", "Luis Campos", "Antero Henrique", "All of these"], 3, "medium", "All held the role at various times."),
        ("Which city do Lille OSC play in?", ["Lyon", "Lille", "Lens", "Rouen"], 1, "easy", "Northern France."),
        ("Who won Ligue 1 with Lille in 2020-21?", ["Christophe Galtier", "Marcelo Bielsa", "Rudi Garcia", "Claude Puel"], 0, "easy", "Ended PSG dominance briefly."),
        ("Which club did Dimitri Payet play for in Ligue 1?", ["Marseille", "Lyon", "Monaco", "Saint-Etienne"], 0, "easy", "Returned to OM in 2017."),
        ("What is the name of the Ligue 1 relegation/promotion play-off?", ["Barrages", "Play-offs", "Ligue 2 final", "No play-off exists"], 0, "hard", "French term for relegation play-off."),
        ("Who is Saint-Etienne's legendary former manager?", ["Robert Herbin", "Arsene Wenger", "Guy Lacombe", "Claude Puel"], 0, "hard", "Led club to multiple titles."),
        ("Which club is based in the principality on the Mediterranean?", ["Nice", "Monaco", "Cannes", "Toulon"], 1, "easy", "Not technically in France."),
        ("Who won the Ligue 1 title in 1999-2000?", ["Monaco", "Paris Saint-Germain", "Bordeaux", "Marseille"], 0, "hard", "Before PSG dominance."),
        ("Which player is known as 'Le Président' at Marseille?", ["Jean-Pierre Papin", "Didier Drogba", "Chris Waddle", "No single player"], 3, "hard", "Trick — Papin was 'Le President' at Marseille fans' call."),
        ("Who managed Lyon during their seven consecutive Ligue 1 titles?", ["Paul Le Guen", "Gérard Houllier", "Hubert Fournier", "Sylvinho"], 1, "medium", "2002-2008 dominance."),
        ("Which club is nicknamed 'Les Girondins'?", ["Bordeaux", "Toulouse", "Montpellier", "Reims"], 0, "medium", "Southwest France."),
        ("Who is the all-time top scorer for Lyon?", ["Alexandre Lacazette", "Bernard Lacombe", "Juninho", "Karim Benzema"], 0, "medium", "Returned to club multiple times."),
        ("Which team plays at Stade Louis II?", ["Nice", "Monaco", "Cannes", "Ajaccio"], 1, "easy", "Monaco's compact stadium."),
        ("Who won the Ligue 1 Player of the Year award most times?", ["Kylian Mbappe", "Zlatan Ibrahimovic", "Eden Hazard", "Jean-Pierre Papin"], 0, "medium", "Five consecutive awards."),
        ("Which club did Laurent Blanc manage in Ligue 1?", ["Marseille", "Paris Saint-Germain", "Bordeaux", "All of these"], 3, "hard", "Managed all three clubs."),
        ("What is the nickname of RC Strasbourg?", ["Les Racing", "Le Racing", "Les Bleu et Blanc", "All used"], 3, "hard", "Alsace club."),
        ("Who scored a famous volley for Lyon against Barcelona in 2019?", ["Memphis Depay", "Nabil Fekir", "Alexandre Lacazette", "Juninho"], 0, "hard", "Champions League group stage."),
        ("Which Ligue 1 club is based in Reims?", ["Stade de Reims", "Chateauroux", "Troyes", "Sochaux"], 0, "medium", "Historic club, champagne region."),
    ],
}

def js_string(s):
    return json.dumps(s, ensure_ascii=False)

def format_question(q, opts, ans, diff, hint, cat_label):
    opts_js = ", ".join(js_string(o) for o in opts)
    return (
        f"          {{ q: {js_string(q)}, opts: [{opts_js}], ans: {ans}, "
        f"cat: {js_string(cat_label)}, diff: {js_string(diff)}, hint: {js_string(hint)} }}"
    )

CAT_LABELS = {
    "premier-league": "Premier League",
    "la-liga": "La Liga",
    "ucl": "Champions League",
    "world-cup": "World Cup",
    "daily": "Daily Challenge",
    "bundesliga": "Bundesliga",
    "serie-a": "Serie A",
    "ligue-1": "Ligue 1",
}

def main():
    lines = ["// Auto-generated extra questions — do not edit by hand; run generate_extra_questions.py", "const QUESTIONS_EXTRA = {"]
    for cat, questions in EXTRA.items():
        label = CAT_LABELS[cat]
        lines.append(f"  '{cat}': [")
        for q, opts, ans, diff, hint in questions:
            lines.append(format_question(q, opts, ans, diff, hint, label) + ",")
        lines.append("  ],")
    lines.append("};")
    lines.append("window.QUESTIONS_EXTRA = QUESTIONS_EXTRA;")
    out = Path(__file__).parent / "questions-extra.js"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out} with {sum(len(v) for v in EXTRA.values())} extra questions")

if __name__ == "__main__":
    main()
