// Extra questions merged into QUESTIONS in data.js (loaded before data.js).
const QUESTIONS_EXTRA = {
  'man-utd': [
    { q: 'Which player scored twice in Manchester United\'s 1999 Champions League final comeback?', opts: ['Teddy Sheringham', 'Ole Gunnar Solskjaer', 'David Beckham', 'Ryan Giggs'], ans: 1, cat: 'Manchester United', diff: 'medium', hint: 'Norwegian super sub in injury time.' },
    { q: 'Who did Manchester United sign from Ajax in 2020?', opts: ['Donny van de Beek', 'Frenkie de Jong', 'Matthijs de Ligt', 'Memphis Depay'], ans: 0, cat: 'Manchester United', diff: 'medium', hint: 'Dutch midfielder who later moved to Everton.' },
    { q: 'Which number shirt is famously associated with George Best at Manchester United?', opts: ['7', '9', '10', '11'], ans: 3, cat: 'Manchester United', diff: 'hard', hint: 'Northern Irish legend of the 1960s.' },
    { q: 'Who was Manchester United\'s top scorer in the 2007-08 Premier League title season?', opts: ['Wayne Rooney', 'Cristiano Ronaldo', 'Carlos Tevez', 'Louis Saha'], ans: 1, cat: 'Manchester United', diff: 'medium', hint: 'He won the Ballon d\'Or that year.' },
    { q: 'Which club did Manchester United beat 8-2 in a famous 2011 Premier League match?', opts: ['Liverpool', 'Arsenal', 'Chelsea', 'Tottenham'], ans: 1, cat: 'Manchester United', diff: 'easy', hint: 'At Old Trafford under Sir Alex Ferguson.' },
    { q: 'Who captained Manchester United in the 2008 Champions League final win?', opts: ['Rio Ferdinand', 'Nemanja Vidic', 'Gary Neville', 'Roy Keane'], ans: 0, cat: 'Manchester United', diff: 'hard', hint: 'English centre-back partnered with Vidic.' },
  ],
  'man-city': [
    { q: 'Which player scored a record five goals for Manchester City in a single Champions League match?', opts: ['Erling Haaland', 'Sergio Aguero', 'Raheem Sterling', 'Kevin De Bruyne'], ans: 0, cat: 'Manchester City', diff: 'medium', hint: 'Norwegian striker vs RB Leipzig.' },
    { q: 'Who was Manchester City\'s first manager after the Abu Dhabi takeover in 2008?', opts: ['Roberto Mancini', 'Mark Hughes', 'Manuel Pellegrini', 'Sven-Goran Eriksson'], ans: 1, cat: 'Manchester City', diff: 'hard', hint: 'Welsh manager replaced by Mancini.' },
    { q: 'Which Manchester City player won the PFA Players\' Player of the Year in 2020?', opts: ['Kevin De Bruyne', 'Raheem Sterling', 'Sergio Aguero', 'David Silva'], ans: 0, cat: 'Manchester City', diff: 'medium', hint: 'Belgian playmaker.' },
    { q: 'What nickname is often used for Manchester City\'s training complex?', opts: ['Carrington', 'Etihad Campus', 'Colney', 'Cobham'], ans: 1, cat: 'Manchester City', diff: 'hard', hint: 'CFA near the Etihad Stadium.' },
    { q: 'Who scored Manchester City\'s first Premier League goal in 1992?', opts: ['Niall Quinn', 'David White', 'Eric Young', 'Paul Walsh'], ans: 1, cat: 'Manchester City', diff: 'hard', hint: 'Against Chelsea at Stamford Bridge.' },
    { q: 'Which Manchester City midfielder scored the winner in the 2023 Champions League final?', opts: ['Kevin De Bruyne', 'Phil Foden', 'Rodri', 'Bernardo Silva'], ans: 2, cat: 'Manchester City', diff: 'easy', hint: 'Spanish midfielder against Inter Milan.' },
  ],
  'chelsea': [
    { q: 'Who scored Chelsea\'s winning penalty in the 2012 Champions League final shootout?', opts: ['Frank Lampard', 'Didier Drogba', 'Ashley Cole', 'Juan Mata'], ans: 1, cat: 'Chelsea FC', diff: 'easy', hint: 'Ivorian striker in Munich.' },
    { q: 'Which Chelsea manager won the Premier League in 2016-17?', opts: ['Jose Mourinho', 'Antonio Conte', 'Carlo Ancelotti', 'Thomas Tuchel'], ans: 1, cat: 'Chelsea FC', diff: 'medium', hint: 'Italian coach using a 3-4-3 system.' },
    { q: 'Who is Chelsea\'s record appearance holder?', opts: ['Frank Lampard', 'Ron Harris', 'John Terry', 'Peter Bonetti'], ans: 1, cat: 'Chelsea FC', diff: 'hard', hint: '795 appearances between 1961 and 1974.' },
    { q: 'Which club did Chelsea sign Cole Palmer from in 2023?', opts: ['Manchester City', 'Liverpool', 'Arsenal', 'Brighton'], ans: 0, cat: 'Chelsea FC', diff: 'easy', hint: 'English attacking midfielder.' },
    { q: 'Who managed Chelsea to their first Champions League title in 2012?', opts: ['Guus Hiddink', 'Roberto Di Matteo', 'Carlo Ancelotti', 'Rafael Benitez'], ans: 1, cat: 'Chelsea FC', diff: 'medium', hint: 'Caretaker manager turned permanent.' },
    { q: 'Which Chelsea legend is nicknamed "The King"?', opts: ['Didier Drogba', 'Peter Osgood', 'Gianfranco Zola', 'Eden Hazard'], ans: 1, cat: 'Chelsea FC', diff: 'hard', hint: 'Striker idol of the 1970s.' },
  ],
  'arsenal': [
    { q: 'Who scored Arsenal\'s famous last-minute winner against Manchester United in 2003?', opts: ['Thierry Henry', 'Robert Pires', 'Sylvain Wiltord', 'Freddie Ljungberg'], ans: 0, cat: 'Arsenal FC', diff: 'medium', hint: 'French striker at Highbury.' },
    { q: 'Which Arsenal player won the Golden Boot in the Invincibles season?', opts: ['Dennis Bergkamp', 'Thierry Henry', 'Robert Pires', 'Patrick Vieira'], ans: 1, cat: 'Arsenal FC', diff: 'easy', hint: '30 league goals in 2003-04.' },
    { q: 'Who did Arsenal sign from Borussia Dortmund in 2018?', opts: ['Pierre-Emerick Aubameyang', 'Henrikh Mkhitaryan', 'Mesut Ozil', 'Alexis Sanchez'], ans: 0, cat: 'Arsenal FC', diff: 'medium', hint: 'Gabonese striker.' },
    { q: 'Which Arsenal manager won the FA Cup in his first two seasons (2014, 2015)?', opts: ['Unai Emery', 'Arsene Wenger', 'Mikel Arteta', 'George Graham'], ans: 1, cat: 'Arsenal FC', diff: 'medium', hint: 'Long-serving French boss.' },
    { q: 'What is Arsenal\'s famous clock end stand at Highbury known as?', opts: ['North Bank', 'Clock End', 'Holte End', 'Kop'], ans: 1, cat: 'Arsenal FC', diff: 'easy', hint: 'Named after the large clock.' },
    { q: 'Who captained Arsenal in the 2006 Champions League final?', opts: ['Patrick Vieira', 'Sol Campbell', 'Kolo Toure', 'Thierry Henry'], ans: 1, cat: 'Arsenal FC', diff: 'hard', hint: 'English centre-back against Barcelona.' },
  ],
  'liverpool': [
    { q: 'Who scored Liverpool\'s fourth goal in the 2005 Champions League final comeback?', opts: ['Steven Gerrard', 'Vladimir Smicer', 'Xabi Alonso', 'Djibril Cisse'], ans: 1, cat: 'Liverpool FC', diff: 'hard', hint: 'Czech midfielder in Istanbul.' },
    { q: 'Which Liverpool player won the Premier League Golden Boot in 2018-19?', opts: ['Mohamed Salah', 'Sadio Mane', 'Roberto Firmino', 'Luis Suarez'], ans: 0, cat: 'Liverpool FC', diff: 'medium', hint: 'Shared with Sadio Mane and Pierre-Emerick Aubameyang.' },
    { q: 'Who is Liverpool\'s current record signing (as of 2024)?', opts: ['Virgil van Dijk', 'Darwin Nunez', 'Dominik Szoboszlai', 'Alexis Mac Allister'], ans: 1, cat: 'Liverpool FC', diff: 'medium', hint: 'Uruguayan striker from Benfica.' },
    { q: 'Which manager led Liverpool to six trophies in 2001 including the UEFA Cup?', opts: ['Rafael Benitez', 'Gerard Houllier', 'Roy Evans', 'Brendan Rodgers'], ans: 1, cat: 'Liverpool FC', diff: 'hard', hint: 'French manager.' },
    { q: 'Who scored Liverpool\'s winner in the 2019 Champions League final?', opts: ['Mohamed Salah', 'Divock Origi', 'Sadio Mane', 'Roberto Firmino'], ans: 0, cat: 'Liverpool FC', diff: 'easy', hint: 'Penalty in the second minute vs Tottenham.' },
    { q: 'Which Liverpool defender won the PFA Player of the Year in 2018-19?', opts: ['Virgil van Dijk', 'Andy Robertson', 'Trent Alexander-Arnold', 'Alisson Becker'], ans: 0, cat: 'Liverpool FC', diff: 'medium', hint: 'Dutch centre-back.' },
  ],
  'real-madrid': [
    { q: 'Who scored the bicycle kick goal for Real Madrid in the 2018 Champions League final?', opts: ['Cristiano Ronaldo', 'Gareth Bale', 'Karim Benzema', 'Marco Asensio'], ans: 1, cat: 'Real Madrid', diff: 'easy', hint: 'Welsh winger against Liverpool.' },
    { q: 'Which Real Madrid player won the Ballon d\'Or in 2022?', opts: ['Vinicius Jr', 'Karim Benzema', 'Luka Modric', 'Jude Bellingham'], ans: 1, cat: 'Real Madrid', diff: 'easy', hint: 'French striker.' },
    { q: 'Who did Real Madrid sign from Chelsea in 2023?', opts: ['Kai Havertz', 'Enzo Fernandez', 'Jude Bellingham', 'Mason Mount'], ans: 2, cat: 'Real Madrid', diff: 'easy', hint: 'English midfielder from Dortmund originally.' },
    { q: 'Which Real Madrid legend is known as "La Quinta del Buitre"?', opts: ['1980s homegrown core', 'Galacticos era', 'BBC attack', 'Yé-yé team'], ans: 0, cat: 'Real Madrid', diff: 'hard', hint: 'Butcher\'s Vulture generation of the 1980s.' },
    { q: 'Who managed Real Madrid to La Decima in 2014?', opts: ['Zinedine Zidane', 'Carlo Ancelotti', 'Jose Mourinho', 'Vicente del Bosque'], ans: 1, cat: 'Real Madrid', diff: 'easy', hint: 'Italian coach.' },
    { q: 'Which Real Madrid goalkeeper is their all-time appearance record holder?', opts: ['Iker Casillas', 'Sergio Ramos', 'Raul', 'Manuel Sanchis'], ans: 0, cat: 'Real Madrid', diff: 'medium', hint: 'Spanish keeper nicknamed San Iker.' },
  ],
  'barcelona': [
    { q: 'Who scored Barcelona\'s winning goal in the 2009 Champions League final?', opts: ['Samuel Eto\'o', 'Lionel Messi', 'Thierry Henry', 'Xavi'], ans: 0, cat: 'FC Barcelona', diff: 'medium', hint: 'Cameroonian striker against Manchester United.' },
    { q: 'Which Barcelona player won the Ballon d\'Or in 2010, 2011, and 2012?', opts: ['Xavi', 'Andres Iniesta', 'Lionel Messi', 'Ronaldinho'], ans: 2, cat: 'FC Barcelona', diff: 'easy', hint: 'Argentine number 10.' },
    { q: 'Who is Barcelona\'s all-time top assist provider?', opts: ['Xavi', 'Lionel Messi', 'Andres Iniesta', 'Luis Suarez'], ans: 1, cat: 'FC Barcelona', diff: 'medium', hint: 'Same player as their top scorer.' },
    { q: 'Which club did Barcelona sign Neymar from in 2013?', opts: ['Santos', 'PSG', 'Porto', 'Gremio'], ans: 0, cat: 'FC Barcelona', diff: 'easy', hint: 'Brazilian club.' },
    { q: 'Who managed Barcelona when they won the treble in 2014-15?', opts: ['Pep Guardiola', 'Luis Enrique', 'Frank Rijkaard', 'Ronald Koeman'], ans: 1, cat: 'FC Barcelona', diff: 'medium', hint: 'Former Barca player.' },
    { q: 'What is the capacity of Barcelona\'s Spotify Camp Nou?', opts: ['85,000', '90,000', '99,354', '105,000'], ans: 2, cat: 'FC Barcelona', diff: 'hard', hint: 'Largest stadium in Europe before renovation.' },
  ],
  'atletico': [
    { q: 'Who scored the winning goal for Atletico in the 2014 Champions League quarter-final vs Barcelona?', opts: ['Diego Costa', 'Koke', 'Raul Garcia', 'Arda Turan'], ans: 2, cat: 'Atletico Madrid', diff: 'hard', hint: '88th-minute header at Camp Nou.' },
    { q: 'Which Atletico Madrid striker won the Golden Boot in La Liga in 2020-21?', opts: ['Antoine Griezmann', 'Luis Suarez', 'Diego Costa', 'Alvaro Morata'], ans: 1, cat: 'Atletico Madrid', diff: 'medium', hint: 'Uruguayan signed from Barcelona.' },
    { q: 'Who did Atletico Madrid beat to win the 2010 Europa League?', opts: ['Arsenal', 'Fulham', 'Liverpool', 'Porto'], ans: 1, cat: 'Atletico Madrid', diff: 'medium', hint: '2-1 in Hamburg.' },
    { q: 'Which Atletico Madrid player is known as "El Cholo"?', opts: ['Diego Simeone', 'Koke', 'Gabi', 'Fernando Torres'], ans: 0, cat: 'Atletico Madrid', diff: 'easy', hint: 'He is the manager, not a player.' },
    { q: 'Who scored Atletico\'s equaliser in the 2014 Champions League final?', opts: ['Diego Godin', 'Diego Costa', 'Koke', 'Miranda'], ans: 0, cat: 'Atletico Madrid', diff: 'medium', hint: 'Uruguayan defender in the 36th minute.' },
    { q: 'Which former Atletico striker returned to the club from Chelsea in 2014?', opts: ['Fernando Torres', 'Diego Costa', 'Alvaro Morata', 'Mario Mandzukic'], ans: 1, cat: 'Atletico Madrid', diff: 'medium', hint: 'Brazil-born Spain striker.' },
  ],
};
